config/routes.rb
Rails.application.routes.draw do
  resources :utentes
  resources :tappes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/index', to: 'home#index', as: 'index'

  get '/home/tappes'
  
  get '/home/utentes'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tappe.rb
class Tappe < ApplicationRecord
    has_one_attached :cover
end

app/models/utente.rb
class Utente < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/tappes_controller.rb
class TappesController < ApplicationController
  before_action :set_tappe, only: %i[ show edit update destroy ]

  # GET /tappes or /tappes.json
  def index
    @tappes = Tappe.all
  end

  # GET /tappes/1 or /tappes/1.json
  def show
  end

  # GET /tappes/new
  def new
    @tappe = Tappe.new
  end

  # GET /tappes/1/edit
  def edit
  end

  # POST /tappes or /tappes.json
  def create
    @tappe = Tappe.new(tappe_params)

    respond_to do |format|
      if @tappe.save
        format.html { redirect_to @tappe, notice: "La tappa è stata creata." }
        format.json { render :show, status: :created, location: @tappe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tappe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tappes/1 or /tappes/1.json
  def update
    respond_to do |format|
      if @tappe.update(tappe_params)
        format.html { redirect_to @tappe, notice: "La tappa è stata modificata." }
        format.json { render :show, status: :ok, location: @tappe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tappe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tappes/1 or /tappes/1.json
  def destroy
    @tappe.destroy
    respond_to do |format|
      format.html { redirect_to tappes_url, notice: "La tappa è stata distrutta." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tappe
      @tappe = Tappe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tappe_params
      params.require(:tappe).permit(:denominazione, :descita, :descing, :partenza, :orari_partenza, :durata, :partecipanti, :cover)
    end
end

app/controllers/utentes_controller.rb
class UtentesController < ApplicationController
  before_action :set_utente, only: %i[ show edit update destroy ]

  # GET /utentes or /utentes.json
  def index
    @utentes = Utente.all
  end

  # GET /utentes/1 or /utentes/1.json
  def show
  end

  # GET /utentes/new
  def new
    @utente = Utente.new
  end

  # GET /utentes/1/edit
  def edit
  end

  # POST /utentes or /utentes.json
  def create
    @utente = Utente.new(utente_params)

    respond_to do |format|
      if @utente.save
        format.html { redirect_to @utente, notice: "L'utente è stato creato." }
        format.json { render :show, status: :created, location: @utente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @utente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utentes/1 or /utentes/1.json
  def update
    respond_to do |format|
      if @utente.update(utente_params)
        format.html { redirect_to @utente, notice: "L'utente è stato modificato." }
        format.json { render :show, status: :ok, location: @utente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @utente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utentes/1 or /utentes/1.json
  def destroy
    @utente.destroy
    respond_to do |format|
      format.html { redirect_to utentes_url, notice: "L'utente è stato eliminato." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utente
      @utente = Utente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def utente_params
      params.require(:utente).permit(:cognome, :nome, :indirizzo, :numero, :annotazioni)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tappes_helper.rb
module TappesHelper
end

app/helpers/utentes_helper.rb
module UtentesHelper
end

app/views/home/index.html.erb
<h5>Vieni a visitare i numerosi castelli della Loira, un esperienza da non perdere.<br>
    Guarda i meravigliosi castelli che potrai visitare:</h5>
    <a class="btn btn-dark btn-lg" href="/tappes" role="button">Vieni a vedere</a>
<br>
<br>


<div class="container">
  <div class="row row-cols-3">
    <div class="col">
    <div class="card"><a href="/tappes/3">
    <p><%= image_tag 'Chenonceau.jpg', class: 'sasso' %></p>
    <div class="card-body">
      <h5 class="card-text">Castello di Chenonceau</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/6">
    <p><%= image_tag 'Amboise.jpg', class: 'sasso' %></p>
    <div class="card-body">
    <h5 class="card-text">Castello di Amboise</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/4">
    <p><%= image_tag 'Blois.jpg', class: 'sasso' %></p>
    <div class="card-body">
    <h5 class="card-text">Castello Reale di Blois</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/5">
    <p><%= image_tag 'cheverny.jpg', class: 'sasso' %></p>
    <div class="card-body">
      <h5 class="card-text">Castello di Cheverny</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/7">
    <p><%= image_tag 'clos.jpg', class: 'sasso' %></p>
    <div class="card-body">
      <h5 class="card-text">Castello di Clos Lucé</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/8">
    <p><%= image_tag 'villandry.jpg', class: 'sasso' %></p>
    <div class="card-body">
      <h5 class="card-text">Castello e giardini Villandry</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/9">
    <p><%= image_tag 'azay.jpg', class: 'sasso' %></p>
    <div class="card-body">
      <h5 class="card-text">Castello di Azay-le-Rideau</h5></div></div>
    </div></a>
    <div class="col">
    <div class="card"><a href="/tappes/10">
    <p><%= image_tag 'angers.jpg', class: 'sasso' %></p>
    <div class="card-body">
      <h5 class="card-text">Castello di Angres</h5></div></div>
    </div></a>

    </div>
    </div>

<br>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="it">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <title>Castelli della Loira</title>
  </head>
  <body>
    


      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/index">Castelli della Loira</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/tappes">Tappe turistiche</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/utentes">Iscrizione</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>




    
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
    <p><%= image_tag 'carosel.jpg',class:'image-fluid' %></p>
  </div>
</div>


    <%= yield %>


<br>

    <footer class="bg-white">
    <div class="container py-5">
      <div class="row py-4">
        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="img/logo.png" alt="" width="180" class="mb-3">
          <p class="font-italic text-muted">Parla con i tuoi amici di queste fantastiche tappe turistiche..</p>
        </div>
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Tappe turistiche</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="/tappes" class="text-muted">Guarda le Tappe</a></li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-6 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Iscrizioni</h6>
          <p class="text-muted mb-4">Iscriviti per tenerti sempre aggiornato.</p>
          <div class="p-1 rounded border">
            <div class="input-group">
              <input type="email" placeholder="Inserisci la tua Email" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
              <div class="input-group-append">
                <button id="button-addon1" type="submit" class="btn btn-link"><i class="fa fa-paper-plane"></i></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tappes/_form.html.erb
<%= form_with(model: tappe) do |form| %>
  <% if tappe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tappe.errors.count, "error") %> prohibited this tappe from being saved:</h2>

      <ul>
        <% tappe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
   
  <div class="container" style="width: 700px">
<body>
  <div class="field">
    <%= form.label :denominazione, class:"lilla" %>
    <%= form.text_field :denominazione, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :descrizione_ita, class:"lilla" %>
    <%= form.text_area :descita, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :descrizione_ing, class:"lilla" %>
    <%= form.text_area :descing, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :partenza, class:"lilla" %>
    <%= form.text_field :partenza, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :orari_partenza, class:"lilla" %>
    <%= form.text_field :orari_partenza, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :durata, class:"lilla" %>
    <%= form.number_field :durata, class:"form-control" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :partecipanti, class:"lilla" %>
    <%= form.number_field :partecipanti, class:"form-control" %>
  </div>
  <br>
  <div class="field">
  <%= form.label 'Foto', class:"lilla" %>
  <%= form.file_field :cover, class:"form-control" %>
 </div>
 <br>
  <div class="actions">
    <%= form.submit 'Crea Tappa', class:"btn btn-warning buttonn" %>
  </div>
  </body>
  </div>
  

<% end %>

app/views/tappes/edit.html.erb
<br>
<div class="d-flex justify-content-center text">
    <h1>Modifica Tappa</h1>
</div>

<%= render 'form', tappe: @tappe %>
<br>
<%= link_to 'Mostra', @tappe, class:"btn btn-info buttonn" %> 

<%= link_to 'Indietro', tappes_path, class:"btn btn-secondary buttonn" %>

<div style="padding: 10px"></div>

app/views/tappes/index.html.erb
<br>

<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center text">
    <h1>Tappe turistiche</h1>
</div>

<br>

<div class="container">
  <div class="row row-cols-3">
    <% @tappes.each do |tappe| %>
    <div class="col">
        <div class="card" style="width: 18rem;">
        <% if tappe.cover.attached? %>
        <%= image_tag url_for(tappe.cover), class:"image img-thumbnail", class: 'imma' %>
        <% end %> 
        <div class="card-body">
          <h5 class="card-title"><%= tappe.denominazione %></h5>
          <p class="card-text"><%= tappe.orari_partenza %></p>
          <%= link_to 'Mostra', tappe, class:"btn btn-info w-100" %> <br><br>
          <%= link_to 'Modifica', edit_tappe_path(tappe), class:"btn btn-warning w-100" %>
          <%= link_to 'Elimina', tappe, method: :delete, data: { confirm: 'Sei sicuro?' }, class:"btn btn-danger w-100" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'Nuova Tappa', new_tappe_path, class:"btn btn-success buttonn" %>

<div style="padding: 20px"></div>

app/views/tappes/new.html.erb
<br>

<h1>Nuova Tappa</h1>

<%= render 'form', tappe: @tappe %>

<br>

<%= link_to 'Indietro', tappes_path, class:"btn btn-secondary buttonn" %>

<div style="padding: 10px"></div>

app/views/tappes/show.html.erb
<br>

<p id="notice"><%= notice %></p>

<p>
<strong>Foto:</strong> <br>
<% if @tappe.cover.attached? %>
 <%= image_tag url_for(@tappe.cover), class:"image img-thumbnail", class: 'imma2' %>
 <% end %>
</p>

<p>
  <strong>Denominazione:</strong> <br>
  <%= @tappe.denominazione %>
</p>

<p>
  <strong>Descrizione(ita):</strong> <br>
  <%= @tappe.descita %>
</p>

<p>
  <strong>Description:</strong> <br>
  <%= @tappe.descing %>
</p>

<p>
  <strong>Partenza:</strong> <br>
  <%= @tappe.partenza %>
</p>

<p>
  <strong>Orari partenza:</strong> <br>
  <%= @tappe.orari_partenza %>
</p>

<p>
  <strong>Durata(ore):</strong> <br>
  <%= @tappe.durata %>
</p>

<p>
  <strong>Partecipanti:</strong> <br>
  <%= @tappe.partecipanti %>
</p>

<%= link_to 'Modifica', edit_tappe_path(@tappe), class:"btn btn-warning buttonn" %> 



<div style="padding: 10px"></div>



<%= link_to 'Indietro', tappes_path, class:"btn btn-secondary buttonn" %>



<div style="padding: 10px"></div>

app/views/utentes/_form.html.erb
<%= form_with(model: utente) do |form| %>
  <% if utente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(utente.errors.count, "error") %> prohibited this utente from being saved:</h2>

      <ul>
        <% utente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="width: 700px">

  <div class="field">
    <%= form.label :cognome, class:"lilla" %>
    <%= form.text_field :cognome, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :nome, class:"lilla" %>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :indirizzo, class:"lilla" %>
    <%= form.text_field :indirizzo, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :numero, class:"lilla" %>
    <%= form.number_field :numero, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :annotazioni, class:"lilla" %>
    <%= form.text_area :annotazioni, class:"form-control" %>
  </div>

<br>

<div>
  <%= form.submit 'Crea Utente', class:"btn btn-warning buttonn" %>
</div>

<br>

</div>

<% end %>

app/views/utentes/edit.html.erb
<br>

<div class="d-flex justify-content-center text">
    <h1>Modifica Utente</h1>
</div>

<%= render 'form', utente: @utente %>

<%= link_to 'MOSTRA', @utente, class:"btn btn-info buttonn" %> 

<%= link_to 'INDIETRO', utentes_path, class:"btn btn-secondary buttonn" %>

<div style="padding: 10px"></div>

app/views/utentes/index.html.erb
<br>

<p id="notice"><%= notice %></p>

<div class="d-flex justify-content-center text">
    <h1>UTENTI</h1>
</div>

<br>

<table class="table">
  <thead>
    <tr>
      <th>Cognome</th>
      <th>Nome</th>
      <th>Indirizzo</th>
      <th>Numero</th>
      <th>Annotazioni</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utentes.each do |utente| %>
      <tr>
        <td><%= utente.cognome %></td>
        <td><%= utente.nome %></td>
        <td><%= utente.indirizzo %></td>
        <td><%= utente.numero %></td>
        <td><%= utente.annotazioni %></td>
        <td><%= link_to 'Mostra', utente, class:"btn btn-info w-100" %></td>
        <td><%= link_to 'Modifica', edit_utente_path(utente), class:"btn btn-warning w-100" %></td>
        <td><%= link_to 'Elimina', utente, method: :delete, data:{ confirm: 'SEI SICURO?' }, class:"btn btn-danger w-100" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuovo Utente', new_utente_path, class:"btn btn-success buttonn" %>

<div style="padding: 20px"></div>

app/views/utentes/new.html.erb
<br>

<h1>NUOVO UTENTE</h1>

<%= render 'form', utente: @utente %>

<%= link_to 'Indietro', utentes_path, class:"btn btn-secondary buttonn" %>

<div style="padding: 10px"></div>

app/views/utentes/show.html.erb
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Cognome:</strong> <br>
  <%= @utente.cognome %>
</p>

<p>
  <strong>Nome:</strong> <br>
  <%= @utente.nome %>
</p>

<p>
  <strong>Indirizzo:</strong> <br>
  <%= @utente.indirizzo %>
</p>

<p>
  <strong>Numero:</strong> <br>
  <%= @utente.numero %>
</p>

<p>
  <strong>Annotazioni:</strong> <br>
  <%= @utente.annotazioni %>
</p>

<%= link_to 'Modifica', edit_utente_path(@utente), class:"btn btn-warning buttonn" %> 

<div style="padding: 10px"></div>

<%= link_to 'Indietro', utentes_path, class:"btn btn-secondary buttonn" %>

<div style="padding: 10px"></div>